name: austinsabado
favicon: null
layout_spectrum: 0.32454836345277727
typography_spectrum: 0.32267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#091e25'
    - '#fefefe'
    - '#49595a'
    - '#7b7f77'
    - '#c6c3b7'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
