name: austinsabado
favicon: null
layout_spectrum: 0.32454836345277727
typography_spectrum: 0.3614373239688575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5910895236302167
  lightness: 0.9003588550258428
  saturation: 0.16621486097574234
  rhythmicContrast: 0.4792711844202131
purpose: []
